# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|

  config.vm.define "ubn-sqd-01" do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.hostname = "ubn-sqd-01"
  config.vm.box_check_update = false
  config.vm.network "public_network", bridge: "br0", dev: "br0", ip: "192.168.88.107"
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 1024
  end
 end
end
